Update resolvconf's dhclient enter hook script for IPv6

diff --git a/etc/dhcp/dhclient-enter-hooks.d/resolvconf b/etc/dhcp/dhclient-enter-hooks.d/resolvconf
--- a/etc/dhcp/dhclient-enter-hooks.d/resolvconf
+++ b/etc/dhcp/dhclient-enter-hooks.d/resolvconf
@@ -1,48 +1,88 @@
 #
-# Script fragment to make dhclient3 work with resolvconf
-#
-# Licensed under the GNU GPL.  See /usr/share/doc/resolvconf/copyright.
+# Script fragment to make dhclient supply nameserver information to resolvconf
 #
 
 # Tips:
 # * Be careful about changing the environment since this is sourced
 # * This script fragment uses bash features
+# * As of isc-dhcp-client 4.2 "$reason" can be one of the following.
+#   (Listed on man page:) MEDIUM(0) PREINIT(0)  BOUND(M)  RENEW(M)  REBIND(M)  REBOOT(M)         EXPIRE(D)  FAIL(D) RELEASE(D)  STOP(D)     NBI(-) TIMEOUT(M)
+#   (Also used in upstream script:)                                                                                                                           ARPCHECK(0), ARPSEND(0)
+#   (Also used in upstream script:) PREINIT6(0) BOUND6(M) RENEW6(M) REBIND6(M)        DEPREF6(0) EXPIRE6(D)         RELEASE6(D) STOP6(D)
+#   Annotations about what happens in the master script for each "reason":
+#   (0) = no-op as far as we are concerned
+#   (M) = runs make_resolv_conf
+#   (D) = downs interface
+#   (-) = not used
+
+rcrd="${interface}.dhclient"
+rcrd_ip6="${interface}.ip6.dhclient"
 
 if [ -x /sbin/resolvconf ] ; then
-	# Do stuff now
+	# For safety, first undefine the nasty default make_resolv_conf()
+	make_resolv_conf() { : ; }
 	case "$reason" in
-		EXPIRE|FAIL|RELEASE|STOP)   # and TIMEOUT too ??
-			# Delete resolv.conf info 
-			[ ! "$interface" ] || /sbin/resolvconf -d "$interface"
-			;;
-	esac
-	# For safety, undefine the nasty default make_resolv_conf()
-	make_resolv_conf() {
-		true
-	}
-	# Define a resolvconf-compatible m_r_c() function which gets run later
-	# (or, in the TIMEOUT case, MAY get run later)
-	case "$reason" in
-		BOUND|RENEW|REBIND|REBOOT|TIMEOUT)
-			make_resolv_conf() {
-				R=""
-				if [ "$new_domain_name_servers" ] && [ "$new_domain_name" ] ; then
-					R="${R}domain $new_domain_name
+	  BOUND|RENEW|REBIND|REBOOT|TIMEOUT)
+		# Define a resolvconf-compatible m_r_c() function
+		# It gets run later (or, in the TIMEOUT case, MAY get run later)
+		make_resolv_conf() {
+			local R
+			local nameserver
+			R=""
+			if [ "$new_domain_name_servers" ] && [ "$new_domain_name" ] ; then
+				R="${R}domain $new_domain_name
 "
+			fi
+			if [ "$new_domain_name_servers" ] && [ "$new_domain_search" ] ; then
+				# The replacement below works around a bug with dhclient 3.1.0 which
+				# separates items with the four characters backslash-zero-three-two
+				# instead of with a space
+				R="${R}search ${new_domain_search//\\032/ }
+"
+			fi
+			for nameserver in $new_domain_name_servers ; do
+				R="${R}nameserver $nameserver
+"
+			done
+			[ ! "$interface" ] || echo -n "$R" | /sbin/resolvconf -a "$rcrd"
+		}
+		;;
+	  BOUND6|RENEW6|REBIND6)
+		# Define a resolvconf-compatible m_r_c() function
+		# It gets run later (or, in the TIMEOUT case, MAY get run later)
+		make_resolv_conf() {
+			local R
+			local nameserver
+			local zone_id
+			R=""
+			if [ "$new_dhcp6_name_servers" ] && [ "$new_dhcp6_domain_search" ] ; then
+				R="${R}search $new_dhcp6_domain_search
+"
+			fi
+			shopt -s nocasematch
+			for nameserver in $new_dhcp6_name_servers ; do
+
+				# If the nameserver has a link-local address
+				# then add a zone ID (interface name) to it.
+				if  [[ "$nameserver" =~ ^fe80:: ]] ; then
+					zone_id="%$interface"
+				else
+					zone_id=""
 				fi
-				if [ "$new_domain_name_servers" ] && [ "$new_domain_search" ] ; then
-					# The replacement below works around a bug with dhclient 3.1.0 which
-					# separates items with the four characters backslash-zero-three-two
-					# instead of with a space
-					R="${R}search ${new_domain_search//\\032/ }
+				R="${R}nameserver $nameserver$zone_id
 "
-				fi
-				for nameserver in $new_domain_name_servers ; do
-					R="${R}nameserver $nameserver
-"
-				done
-				[ ! "$interface" ] || echo -n "$R" | /sbin/resolvconf -a "$interface"
-			}
-			;;
+			done
+			shopt -u nocasematch
+			[ ! "$interface" ] || echo -n "$R" | /sbin/resolvconf -a "$rcrd_ip6"
+		}
+		;;
+	  EXPIRE|FAIL|RELEASE|STOP)
+		# Delete resolv.conf info 
+		[ ! "$interface" ] || /sbin/resolvconf -d "$rcrd"
+		;;
+	  EXPIRE6|RELEASE6|STOP6)
+		# Delete resolv.conf info 
+		[ ! "$interface" ] || /sbin/resolvconf -d "$rcrd_ip6"
+		;;
 	esac
 fi
