Updates as described in debian/changelog

diff --git a/debian/init b/debian/init
--- a/debian/init
+++ b/debian/init
@@ -3,8 +3,6 @@
 # resolvconf  --  Nameserver information manager
 #
 # This script is part of the resolvconf package
-#
-# Jun 2003 - July 2005: Written by Thomas Hood
 
 # Don't use set -e; check return status instead
 
@@ -17,18 +15,15 @@ IFACE_DIR="${RUN_DIR}/interface"
 RESOLVCONF_FILE="${RUN_DIR}/resolv.conf"
 ENABLE_UPDATES_FLAGFILE="${RUN_DIR}/enable-updates"
 
-if [ -r /lib/lsb/init-functions ] ; then
-	. /lib/lsb/init-functions
-	print_warning_msg() { log_warning_msg "$@" ; }
-	print_error_msg() { log_failure_msg "${MYNAME}: Error: $*" ; }
-	print_begin_msg() { log_begin_msg "$@" ; }
-	print_end_msg_and_exit() { log_end_msg "$1" ; exit $1 ; }
-else
-	print_warning_msg() { echo -n "$*" >&2 ; }
-	print_error_msg() { echo "${MYNAME}: Error: $*" >&2 ; }
-	print_begin_msg() { echo -n "$*" ; }
-	print_end_msg_and_exit() { case "$1" in (0) echo "${2}." ;; (*) echo "${3}." ;; esac ; exit $1 ; }
-fi
+. /lib/lsb/init-functions
+
+# $1 EXITSTATUS
+# [$2 MESSAGE]
+log_action_end_msg_and_exit()
+{
+	log_action_end_msg "$1" ${2:+"$2"}
+	exit $1
+}
 
 update()
 {
@@ -53,44 +48,44 @@ start)
 	# The "start" method should _only_ be used at boot time.
 	# If you want to update the resolv.conf file then use "reload".
 	# On package upgrade, don't run this.
-	print_begin_msg "Setting up resolvconf..."
+	log_action_begin_msg "Setting up resolvconf"
 	umask 022
 	if [ ! -d "$RUN_DIR" ] ; then
-		[ -L "$RUN_DIR" ] || print_end_msg_and_exit 1 "" "failed: $RUN_DIR is neither a directory nor a symbolic link"
+		[ -L "$RUN_DIR" ] || log_action_end_msg_and_exit 1 "$RUN_DIR is neither a directory nor a symbolic link"
 		# Target of symlink is not a dir
-		{ RUN_CANONICALDIR="$(readlink -f "$RUN_DIR")" && [ "$RUN_CANONICALDIR" ] ; } || print_end_msg_and_exit 1 "" "failed: canonical path of the run directory could not be determined"
+		{ RUN_CANONICALDIR="$(readlink -f "$RUN_DIR")" && [ "$RUN_CANONICALDIR" ] ; } || log_action_end_msg_and_exit 1 "canonical path of the run directory could not be determined"
 		# Create directory at the target
-		mkdir "$RUN_CANONICALDIR" || print_end_msg_and_exit 1 "" "failed creating directory $RUN_CANONICALDIR"
+		mkdir "$RUN_CANONICALDIR" || log_action_end_msg_and_exit 1 "error creating directory $RUN_CANONICALDIR"
 	fi
 	# The run directory exists
 
 	if [ -d "${RUN_DIR}/interface" ] ; then
 		rm -f ${RUN_DIR}/interface/*
 	else
-		mkdir "${RUN_DIR}/interface" || print_end_msg_and_exit 1 "" "failed creating directory ${RUN_DIR}/interface"
+		mkdir "${RUN_DIR}/interface" || log_action_end_msg_and_exit 1 "error creating directory ${RUN_DIR}/interface"
 	fi
 	# The interface directory exists
 
-	enable_updates || print_end_msg_and_exit 1 "" "failed enabling updates"
+	enable_updates || log_action_end_msg_and_exit 1 "could not enable updates"
 	update -i
-	print_end_msg_and_exit "$?" "done" "failed"
+	log_action_end_msg_and_exit "$?"
 	;;
 stop)
 	# The "stop" method should only be used at shutdown time.
-	print_begin_msg "Stopping resolvconf..."
+	log_action_begin_msg "Stopping resolvconf"
 	disable_updates
-	print_end_msg_and_exit "$?" "done" "failed"
+	log_action_end_msg_and_exit "$?"
 	;;
 restart)
-	print_begin_msg "Restarting resolvconf..."
-	[ -d "${RUN_DIR}/interface" ] || { print_error_msg "${RUN_DIR}/interface is not a directory" ; exit 1 ; }
-	enable_updates || print_end_msg_and_exit 1 "" "failed enabling updates"
+	log_action_begin_msg "Restarting resolvconf"
+	[ -d "${RUN_DIR}/interface" ] || log_action_end_msg_and_exit 1 "${RUN_DIR}/interface is not a directory"
+	enable_updates || log_action_end_msg_and_exit 1 "could not enabling updates"
 	update
-	print_end_msg_and_exit $? "done" "failed"
+	log_action_end_msg_and_exit "$?"
 	;;
 reload|force-reload)
 	# Do it silently
-	[ -d "${RUN_DIR}/interface" ] || { print_error_msg "${RUN_DIR}/interface is not a directory" ; exit 1 ; }
+	[ -d "${RUN_DIR}/interface" ] || { log_failure_msg "${RUN_DIR}/interface is not a directory" ; exit 1 ; }
 	update
 	exit $?
 	;;
@@ -103,7 +98,7 @@ disable-updates)
 	exit $?
 	;;
 *)
-	print_warning_msg "Usage: /etc/init.d/resolvconf {start|stop|reload|restart|force-reload|enable-updates|disable-updates}"
+	echo "Usage: /etc/init.d/resolvconf {start|stop|reload|restart|force-reload|enable-updates|disable-updates}" >&2
 	exit 3
 	;;
 esac
